lib/active_merchant/billing/gateways/nab_transact.rb, test/remote/gateways/remote_nab_transact_test.rb, test/unit/gateways/nab_transact_test.rb
Allows scrubbing of NAB transact transcripts.
Note: this was branched off the latest from upstream, so there are lots of commits before it. See #3
=> Add scrubbing support for nab transact

lib/active_merchant/billing/gateways/payment_solutions.rb, test/fixtures.yml, test/remote/gateways/remote_payment_solutions_test.rb, test/unit/gateways/payment_solutions_test.rb
PSI is not a gateway per-se, more like an NGO CRM that in term uses Authorized.net in the background. This implementation ONLY implements the `purchase` method as that's the only function we will be using for our customer. This implementation WILL NOT be pushed to ActiveMerchant as it's not a proper payment gateway and won't get merged, I suspect.
Note: the live_url has NOT been tested yet.
[#115453715]
=> Adding support for PSI

lib/active_merchant/billing/gateways/world_net.rb, test/remote/gateways/remote_world_net_test.rb, test/unit/gateways/world_net_test.rb
This commit adds support for the `store` and `unstore` methods (secure card registration and removal), fixes a few rubocop warnings.
=> Implement support for `store` and `unstore`

lib/active_merchant/billing/gateways/banwire.rb, test/remote/gateways/remote_banwire_test.rb, test/unit/gateways/banwire_test.rb
This commit adds support for tokenisation via the `recurrentes` API
http://docs.banwire.com/recurrentes to Banwire.
The one off payments for tokens seems to require an account, I have not
added tests for that yet.
[#119226831]
=> Adds basic tokenisation support for banwire

lib/active_merchant/billing/gateways/payment_solutions.rb, test/remote/gateways/remote_payment_solutions_test.rb
This adds the ability to pass an additional option, `:market_source` (which can be up to 200 chars).
[#120107569]
=> Add ability to pass market source in payment info

lib/active_merchant/billing/gateways/orbital.rb, test/remote/gateways/remote_orbital_test.rb, test/unit/gateways/orbital_test.rb
Adding support for scrubbing to Orbital gateway. It would seem that
every test suite sent by Orbital might require different test cards, I
am only committing the small change to point to the correct fixture
hash.
[#117095839]
=> Add support for scrubbing to Orbital

lib/active_merchant/billing/gateways/payment_solutions.rb, test/remote/gateways/remote_payment_solutions_test.rb
During the development of this gateway implementation, I hardcoded `false` in `Donor.SendEmail` however the correct implementation should check if the `address[:email]` parameter has been supplied and change between `true` and `false` accordingly.
[#122001267]
=> Pass true to SendEmail when address[:email] exists

lib/active_merchant/billing/gateways/flo2cash.rb, test/remote/gateways/remote_flo2cash_test.rb, test/unit/gateways/flo2cash_test.rb
Implements tokenisation for Flo2Cash. Adds support for `store`, `unstore` and tests for purchase with tokenised card.
Flo2Cash has two methods to tokenise, `AddCard` and `AddCardWithUniqueReference`, we implement both conditionally on the presence of `options[:order_id]`. The main difference between both is simply that one allows the unique reference to be associated to the token, which can then be used by the merchant to search for the token using that reference, the other just creates a simple token.
Refactor the `purchase` method to use the `ProcessPurchase` at the suggestion from support at Flo2Cash since most of their merchants are not using `ProcessAuthorise` (that's what I have been told).
Note: I am not entirely sure why the `purchase` was original set up as `auth` + `capture` so …
=> Implement store for Flo2Cash

lib/active_merchant/billing/gateways/secure_co.rb, test/remote/gateways/remote_secure_co_test.rb, test/unit/gateways/secure_co_test.rb
- Added the `store` method.
- Updated `purchase`,  `authorize` and `verify` methods to accept a token.
- Added unit tests and integration tests
- Minor text changes
=> Add 'store' to SecureCo gateway

lib/active_merchant/billing/gateways/charity_engine.rb, test/fixtures.yml, test/remote/gateways/remote_charity_engine_test.rb, test/unit/gateways/charity_engine_test.rb
Implement a very basic gateway, with only support for `purchase` for
Charity Engine. Charity Engine is more a CRM than it is a gateway, they
use Authorize.net upstream.
Several parameters can be passed optionally, like the whole structure
in the `options[:customer]` or `options[:attribution]` (see the remote
gateway test for samples) that will be passed on to CE.
This is not a proper ActiveMerchant gateway implementation, thus I am not sending it upstream, only to `waysact/master`.
=> Add support for payments using Charity Engine

lib/active_merchant/billing/gateways/merchant_first.rb
Merchant First (well, an upstream payment processor) requires that the
CountryCode be passed together with the TransactionData.
=> Add optional CountryCode element in transaction data

lib/active_merchant/billing/gateways/charity_engine.rb, test/remote/gateways/remote_charity_engine_test.rb
This change adds support for optional fields (`code1` to `code8`) that
can be passed in the `attribution` data structure in a `tracking_codes:
{}` hash, example:
```
attribution: {
response_channel_id: ‘123’,
tracking_codes: {
code3: ‘some value’,
code6: ‘another value’
},
}
```
=> Add support for tracking codes within attribution

lib/active_merchant/billing/gateways/openpay.rb, test/remote/gateways/remote_openpay_test.rb, test/unit/gateways/openpay_test.rb
One of our customers Openpay account is configured (can’t find the proper reason from their support as to why) to use the “comercio” configuration and thus we need to use the ephemeral “token” (mandatory) prior to calling the charges API.
I extended the `purchase` method to now allow the multi-step call to create a `token` and use the resulting `id` as the `source_id` for the `charges` if the `options[:use_token]` is present with any value.
This is a bit of a hack, however that way we can call the `charges` endpoint or do the workflow depending on the customer's account configuration.
=> Add support for purchases using ephemeral tokens

lib/active_merchant/billing/gateways/charity_engine.rb, test/remote/gateways/remote_charity_engine_test.rb
As requested, CE always requires this field to be sent so they can
process and send the invoice to the customer.
Small update on the options Hash for the remote test, passing the label
in code6.
=> [CE] Add SendReceipt boolean defaults to TRUE

lib/active_merchant/billing/gateways/secure_pay_au.rb, test/remote/gateways/remote_secure_pay_au_test.rb, test/unit/gateways/secure_pay_au_test.rb
* Introduces the ability to store cards as tokens (see
https://www.securepay.com.au/_uploads/files/Secure_XML_API_Integrat.pdf
section 6.1.2). To tokenise using that option, pass
`options[:store_as_token] = true` (or any value to that Hash key).
* Updates the API URLs
* Send `Content-Type: text/xml` in the header
Note: I am not pushing this upstream as it's not particular nice code (duplication).
=> Add support for storing cards as tokens in SecurePayAU

lib/active_merchant/billing/gateways/payment_express.rb, test/remote/gateways/remote_payment_express_test.rb
Payment Express required us to use uat.paymentexpress.com instead of
the sec.paymentexpress.com which is documented in their PxPost docs and
the default active merchant implementation.
Also add the login details to the transcript scrubbing to ensure we
don’t leak sensitive information.
In the remote tests, update the error we receive with invalid
credentials, use a non-default CVV for the tests, in particular this is
relevant for the scrubbing tests, as 432 doesn’t seem to occur
regularly and thus doesn’t trigger a false failure. Also add tests for
the login and password.
=> Scrub login and update URLs for payment express

lib/active_merchant/billing/gateways/charity_engine.rb
The field that contains the province in the customer’s contact details
is named AddressState, unlike the billing address where it’s using the
pattern of AddressStateProvince.
=> Rename AddressStateProvince to AddressState

lib/active_merchant/billing/gateways/payment_express.rb
As recommended by the Payment Express support team, we need to pass
`<TxnType>Tokenize</TxnType>` instead of `<TxnType>Validate</TxnType>`
for `store`. Note: this `TxnType` is not on their documentation however
I have been told, upon specific question, that this is valid and can be
used.
=> Use Tokenize TxnType for tokenisation

lib/active_merchant/connection.rb
Rather than using ActiveMerchant's outdated CA certificates, use the
system ones. This resolves issues with Merchant First.
This was based on a suggestion found in a Github issue here:
activemerchant#1643 (comment) and
https://github.com/dxw/active_merchant/pull/2
=> :bug: Use OpenSSL CA bundle instead of AM's

lib/active_merchant/billing/gateways/nab_transact.rb
NAB support have confirmed the correct URL is
https://demo.transact.nab.com.au/xmlapi/payment
=> Change NAB Transact test url

lib/active_merchant/billing/gateways/payment_solutions.rb
Use an output Nokogiri option to generate the XML without indentation (remove extra carriage returns and whitespace).
See https://stackoverflow.com/questions/8406251/nokogiri-to-xml-without-carriage-returns
=> Nokogiri option to output XML without indentation

lib/active_merchant/billing/gateways/payment_solutions.rb
As required by PSI, the XML attributes in the sequence should be added in a specific order.
=> Re-order XML attributes for customer data in PSI

lib/active_merchant/billing/gateways/payment_solutions.rb
The SendEmail attribute needs to be set to `false` based on another attribute that’s no longer just the presence or absence of `address[:email]` … the attribute we’ll be passing is `options[:send_email]` and it’ll be a boolean … so if it’s absent we default to `false`.
=> SendEmail is false unless explicitly set otherwise

lib/active_merchant/billing/gateways/payment_solutions.rb
D’oh!!! #facepalm … the `.present?` here is from when I looked at using it instead of the `empty?` and forgot to remove it. I am using `.empty?` to keep with the style I adopted in this implementation and use the same method throughout.
=> Remove .present? lingering from prev attempt

lib/active_merchant/billing/gateways/authorize_net_arb.rb
It's a very crude implementation and since the API shares a lot of the same XML attributes as the `AuthorizeNetGateway` I just copied that ...
=> Add scrubbing support for Authorize.Net ARB

lib/active_merchant/billing/gateways/mobilexpress.rb, test/fixtures.yml, test/remote/gateways/remote_mobilexpress_test.rb, test/unit/gateways/mobilexpress_test.rb
Mobilexpress gateway implementation for Turkish Lira. Mobilexpress supports multiple currencies however those are not passed as parameters, they are configured on the account and the POS_ID indicates the currency to be used. Same with credit card types, there are no specific parameters to be passed, that's all done server-side based on the BIN.
Note: this gateway implementation does not contain support for authorisation, capture, void or refund. Mobilexpress does support it however none of our customers use those methods.
=> Add support for Mobilexpress gateway

lib/active_merchant/billing/gateways/zuora.rb, test/fixtures.yml, test/remote/gateways/remote_zuora_test.rb, test/unit/gateways/zuora_test.rb
Adds the skeleton for Zuora that implements tokenisation only and only for Australia for the time being. I am not 100% familiar with all the currencies and territories that are supported by Zuora, given their size, it's probably quite a lot.
=> Add skeleton for Zuora (only store)

lib/active_merchant/billing/gateways/ezidebit.rb, test/fixtures.yml, test/remote/gateways/remote_ezidebit_test.rb, test/unit/gateways/ezidebit_test.rb
Ezidebit only seems to implement `purchase` and `store` via the SOAP API and not the usual suspects of `authorise`, `capture`, `void` and `refund`.
When using `purchase` we return the `receipt_id` and the `exchange_payment_id` returned values separated by a `|` (pipe) character so that a customer can have access to both and select which one they want to use in their downstream applications.
=> Add support for Ezidebit gateway

lib/active_merchant/billing/gateways/ezidebit.rb, test/remote/gateways/remote_ezidebit_test.rb, test/unit/gateways/ezidebit_test.rb
Introduces support for creating recurring payment schedules in Ezidebit.
This code assumes the caller will deal with the specific values to pass into the `options` Hash to set the correct values.
Details on the fields required are available at https://www.getpayments.com/docs/#createschedule
=> Adding recurring support to Ezidebit

lib/active_merchant/billing/gateways/ezidebit.rb
The Username field can be used to add additional metadata to some transactions/customers.
=> Add username field to payloads that support it

lib/active_merchant/billing/gateways/bambora_na.rb, test/fixtures.yml, test/remote/gateways/remote_bambora_na_test.rb, test/unit/gateways/bambora_na_test.rb
Bambora North America has a different API than Beamstream (old XML/SOAP API) or other regions.
This implements a basic support (just `purchase` and `store` methods).
There's still more todo to finish it to be a proper ActiveMerchant implementation, i.e. use the error code mapping to return the right ActiveMerchant errors and also add the `authorisation|capture|void|refund` methods.
```
Loaded suite test/remote/gateways/remote_bambora_na_test
Started
......
Finished in 12.076706 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
6 tests, 12 assertions, 0 failures, 0 errors, 0 pendings, 0 …
```
=> Add basic support for Bambora NA

lib/active_merchant/billing/gateways/mobilexpress.rb
The payload for the `store` method has a different XML element name.
=> Also scrub card number in SaveCreditCard

test/remote/gateways/remote_payment_solutions_test.rb
This updates the remote tests for PSI as they now use Braintree as their backend, instead of Authorize.net
=> Update test cc and amount for PSI

lib/active_merchant/billing/gateways/mobilexpress.rb, test/remote/gateways/remote_mobilexpress_test.rb
`ProcessPaymentWithCard` now adds a unique transaction_id if `order_id` is not passed as options and can also add customer data which was previously undocumented.
This should address the issues raised by our customers using Mobilexpress that wanted those details logged with the purchase transactions.
=> Add previously undocumented options to purchase

lib/active_merchant/billing/gateways/payment_solutions.rb, test/remote/gateways/remote_payment_solutions_test.rb
Adds the `SideCar` XML payload with a hardcoded `field_c6` name and value that will be passed conditionally based on a custom field.
=> Add support for SideCar payload in PSI

lib/active_merchant/billing/gateways/payment_solutions.rb
Despite the fact that initially the request was to send the `Value` empty, we've been requested to only send the `SideCar` when the value is present and non nil.
=> Only send SideCar when option is present

lib/active_merchant/billing/gateways/world_net.rb, test/remote/gateways/remote_world_net_test.rb, test/unit/gateways/world_net_test.rb
This introduces a basic support for subscriptions in World Net using `ADDSUBSCRIPTION ` with the nested `NEWSTOREDSUBSCRIPTIONINFO` element so that we create the stored subscription on each new request.
Note: this is very basic and does not allow complex combinations where the customers would want to create stored subscriptions separately and then add subscriptions to those, this is a request from our customer that wants to use this.
=> Add ARB support to World Net

lib/active_merchant/billing/gateways/authorize_net_arb.rb, test/unit/gateways/authorize_net_arb_test.rb
Unnecessary since we now maintain our own fork (we've added plenty of gateways, etc) and it's extremely unlikely that our fork will be merged upstream.
=> Silence deprecation notices in AuthorizeNet
